### ISSUE TITLE
dpkg: dependency problems prevent configuration of toft-lxc

### ISSUE THREAD

**Issue by whatupdave** [exceedhl/toft#12]
Using the provided `ubuntu-1104-server-i386` base box I get this error on installing the toft package:

``` bash
vagrant@natty:~$ sudo dpkg -i toft-lxc_0.0.11_all.deb
Selecting previously deselected package toft-lxc.
(Reading database ... 49764 files and directories currently installed.)
Unpacking toft-lxc (from toft-lxc_0.0.11_all.deb) ...
dpkg: dependency problems prevent configuration of toft-lxc:
 toft-lxc depends on rpm; however:
  Package rpm is not installed.
 toft-lxc depends on lxc; however:
  Package lxc is not installed.
 toft-lxc depends on bridge-utils; however:
  Package bridge-utils is not installed.
 toft-lxc depends on debootstrap; however:
  Package debootstrap is not installed.
 toft-lxc depends on dhcp3-server; however:
  Package dhcp3-server is not installed.
 toft-lxc depends on bind9; however:
  Package bind9 is not installed.
 toft-lxc depends on ntp; however:
  Package ntp is not installed.
dpkg: error processing toft-lxc (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 toft-lxc
```

**Comment by exceedhl** [comment]
Try run `sudo apt-get -f install`

On Thu, May 17, 2012 at 8:08 AM, Dave Newman
reply@reply.github.com
wrote:

> Using the provided `ubuntu-1104-server-i386` base box I get this error on installing the toft package:
> 
> ``` bash
> vagrant@natty:~$ sudo dpkg -i toft-lxc_0.0.11_all.deb
> Selecting previously deselected package toft-lxc.
> (Reading database ... 49764 files and directories currently installed.)
> Unpacking toft-lxc (from toft-lxc_0.0.11_all.deb) ...
> dpkg: dependency problems prevent configuration of toft-lxc:
>  toft-lxc depends on rpm; however:
>  Package rpm is not installed.
>  toft-lxc depends on lxc; however:
>  Package lxc is not installed.
>  toft-lxc depends on bridge-utils; however:
>  Package bridge-utils is not installed.
>  toft-lxc depends on debootstrap; however:
>  Package debootstrap is not installed.
>  toft-lxc depends on dhcp3-server; however:
>  Package dhcp3-server is not installed.
>  toft-lxc depends on bind9; however:
>  Package bind9 is not installed.
>  toft-lxc depends on ntp; however:
>  Package ntp is not installed.
> dpkg: error processing toft-lxc (--install):
>  dependency problems - leaving unconfigured
> Errors were encountered while processing:
>  toft-lxc
> ```
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/exceedhl/toft/issues/12

## 

Yours,
Liang
