### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by acrmp** [exceedhl/toft#4]
Hi guys,

Great looking tool. What license is Toft licensed under? I had a look but couldn't see anything.

It would be handy if the license was named in the gemspec and a LICENSE file provided at the root of the project.

Cheers,

Andrew.

**Comment by exceedhl** [comment]
Feel free to use it. Don't worry about license.

**Comment by acrmp** [comment]
:-) Thanks. I appreciate the sentiment.

Unfortunately due to us all living in a world with lawyers (very nice people that they all are too) you may exclude people from using Toft by not stating a license.

**Comment by exceedhl** [comment]
MIT license is put into the README file.

**Comment by acrmp** [comment]
Awesome. Thanks!
