### ISSUE TITLE
Toft.cookbook_path should accept an array of paths

### ISSUE THREAD

**Issue by bryanwb** [exceedhl/toft#5]
Many of us use two or more directories. You have to use two directories if you use librarian

**Comment by exceedhl** [comment]
Sounds a good idea, I will add it to the next release.

**Comment by rosstimson** [comment]
As a Librarian user I'd love to see this implemented, all of my custom stuff such as recipes for testing are in `site-cookbooks/` as Librarian takes control of the standard `cookbooks/` directory.
