### ISSUE TITLE
toft doesn't work with ruby 1.9

### ISSUE THREAD

**Issue by bryanwb** [exceedhl/toft#7]
require 'toft' fails because 'ping' library cannot be found
pry> require 'toft'
LoadError: cannot load such file -- ping

https://github.com/exceedhl/toft/blob/master/lib/toft/node.rb#L3

hey guys, any idea what gem provides 'ping' ?

edit:  unfortunately ping is not in the stdlib for ruby 1.9\*  . there is a net-ping available as a separate gem, not sure how compatible it is with the old ping

btw, I love toft! I really hope to use it as a critical tool for testing my chef cookbooks. Bravo to Frank and Huang Liang. Xie Xie ni  Wo hen kai xin gen toft

**Comment by exceedhl** [comment]
Ping is part of ruby standard library, so it should not require any specific gem.

**Comment by rosstimson** [comment]
Doesn't look like ping is part of the Ruby 1.9 stdlib to me, seems like net-ping gem as suggested by @bryanwb is the way to progress with this one.

**Comment by rosstimson** [comment]
Come across this fork by @TensorWrench where this looks to be fixed without adding an additional dependency.  This commit maybe be worth looking at / consider pulling:  https://github.com/TensorWrench/toft/commit/2b0ae34cc90f5ecc3111191d014aa406b9843853

**Comment by exceedhl** [comment]
Thanks, will add it.
